#!/bin/bash

apt-get update && apt-get upgrade
apt-get install libpq-dev postgresql postgresql-contrib nginx python3-pip
apt install snapd
snap install core
snap refresh core
snap install --classic certbot
ln -s /snap/bin/certbot /usr/bin/certbot
cp Full_install/emperor.uwsgi.service /etc/systemd/system/.
/etc/init.d/nginx start
systemctl enable emperor.uwsgi.service
systemctl enable nginx.service
systemctl start emperor.uwsgi.service
pip3 install virtualenv psycopg2 uwsgi
mkdir /etc/uwsgi
mkdir /etc/uwsgi/vassals
mkdir /var/log/uwsgi

command_psql="psql -c \"create user evgen;\""
su - postgres -c "$command_psql"

cat temp_default.txt > /etc/nginx/sites-enabled/default

echo "colorscheme blue" > ~/vimrc
